name: Simple Test

on:
  workflow_dispatch:
    inputs:
      testInput:
        description: 'Test input'
        required: true
        default: 'test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Echo input
        run: echo "Input is ${{ github.event.inputs.testInput }}" 